name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  origin_branch:
    description: 'Main branch'
    required: true
    default: 'main'
  branch:
    description: 'Branch to send updates'
    required: true
    default: 'hotfix'

outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'node20'
  main: 'dist/index.js'


