name: 'Branch syncker'
description: 'Merge branches with rebase and push changes to target branch'
inputs:
  source-branch:
    description: 'Source branch'
    default: 'main'
  target-branch:
    description: 'Branch to send updates'
    required: true
  slack-webhook:
    description: 'Slack webhook URL'
    required: true
  user:
    description: 'Git user'
    default: 'Branch Sync'
  email:
    description: 'Git email'
    default: 'sample@mail.com'
outputs:
  rebase:
    description: 'The result of the rebase'
runs:
  using: 'node20'
  main: 'dist/index.js'


