name: 'Branch syncker'
description: 'Merge branches with rebase and push changes to target branch'
inputs:
  source-branch:
    description: 'Source branch'
    required: true
    default: 'main'
  target-branch:
    description: 'Branch to send updates'
    required: true
  slack-webhook:
    description: 'Slack webhook URL'
    required: true
outputs:
  rebase:
    description: 'The result of the rebase'
runs:
  using: 'node20'
  main: 'dist/index.js'


