on: [push]

permissions:
  actions: write
  checks: write
  contents: write
  pull-requests: write

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Git User
        run: |
          git config user.name "Branch Sync"
          git config user.email "sample@mail.com"
      - name: Hello world action step
        uses: ./ # Uses an action in the root directory
        id: hello
        with:
          origin-branch: 'main'
          branch: 'hotfix'
          slack-webhook: 'https://hooks.slack.com/services/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'
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
