on: [push]

permissions:
  actions: write
  checks: write
  contents: write
  pull-requests: write

jobs:
  branch-syncker:
    runs-on: ubuntu-latest
    name: Merge branches
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
#      - name: Setup Git User
#        run: |
#          git config user.name "Branch Sync"
#          git config user.email "sample@mail.com"
      - name: Sync main to hotfix
        uses: ./
        id: hotfix
        with:
          source-branch: 'main'
          target-branch: 'hotfix'
          slack-webhook: ${{ secrets.SLACK_WEBHOOK }}
      - name: Get the output time
        run: echo "The result ${{ steps.hotfix.outputs.sourceBranch }}->${{ steps.hotfix.outputs.targetBranch }}:${{ steps.hotfix.outputs.success }}"
