on: [push]

permissions:
  actions: write
  checks: write
  contents: write
  pull-requests: write

jobs:
  branch-syncker:
    runs-on: ubuntu-latest
    name: Sync branches
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Sync main to hotfix
        uses: ./
        id: hotfix
        with:
          source-branch: 'main'
          target-branch: 'hotfix'
          slack-webhook: ${{ secrets.SLACK_WEBHOOK }}
      - name: Sync main to squad-beta
        uses: ./
        id: squad-beta
        with:
          source-branch: 'main'
          target-branch: 'squad-beta'
          slack-webhook: ${{ secrets.SLACK_WEBHOOK }}
      - name: Merge output
        run: echo "The result ${{ steps.squad-beta.outputs.rebase.sourceBranch }}->${{ steps.squad-beta.outputs.rebase.targetBranch }}:${{ steps.squad-beta.outputs.rebase.success }}"
